### ISSUE TITLE
خطا هنگام دیکریپت کردن در php

### ISSUE THREAD

**Issue by miladkantoori** [alirezaashrafi/Codia#1]
سلام من یک متن که شامل انگلیسی و فارسی میشه رو در اندروید کد میکنم و در سمت سرور دیکد میکنم ولی در سرور با خطا مواجه میشه و متن دیکد شده فقط شامل انگلیسی میشه و فارسی ها به مشکل بر خوردن
[28-Mar-2020 21:15:37 Asia/tehran] PHP Notice:  Undefined offset: 0 in /home/mysite.ir/Codia.php on line 28

**Comment by alirezaashrafi** [comment]
I'm sorry for being late. I have not received notification for this issue.
Milad, Unfortunetly. this project has been deprecated and no longer supported. Because I'm not developing Android anymore, I appreciate any helps to fix the issues and improve the project.
